Added support for permit2 and TransferWithAuth deposit schemes
zkBob/zkbob-client-js pull request #140
Opened 2023-06-19 20:16 UTC by EvgenKor

To perform new deposit schemes (via Uniswap Permit2, via TransferWithAuthorization for USDC token) the following changes were prepared:
1. All signature creating\recovering routines were moved to the new `DepositSigner` object (similar with relayer codebase)
2. Each pool config should contain new property `depositScheme` of `DepositType` type (`permit`, `permit2`, `auth`, `approve`)
3. `depositPermittable` was renamed to `deposit` - it's an universal deposit routine now which worked with configured deposit type
4. Signing callback has a single parameter of `SignatureRequest` type. It contains signature type (personal\typed) and data to sign. The data depends on signature type. In case of personal signature request it contains a nullifier in hex-string 0x-prefixed format. In case of signing typed data it contains object with the following fields: `types`, `domain`, `primaryType`, `message`
5. The old method deposit was removed at all (the new one can perform old deposits via approval)
6. `depositPermittableEphemeral` was renamed to `depositEphemeral`
7. The ephemeral deposit support for permit2\approve schemes was added (now it makes an approve if needed)
8. In the pool configuration added optional field `minTxAmount` (will be helpful for WETH pools). When it's undefined the default `0.05` amount will used

2023-06-20 08:03 UTC, k1rill-fedoseev requested changes

2023-06-20 08:03 UTC, k1rill-fedoseev commented on src/config.ts
> +  SaltedPermit = 'permit',  // EIP-2612 (regular permit)
Let's mention that it's a non standard EIP-2612, since we have also added salt to it

2023-06-21 13:26 UTC, EvgenKor commented on src/signers/usdc-signer.ts
> +        const bitPos = BigInt(data.nullifier) & 0xFFn
Yes, it's my fault. Fixed in https://github.com/zkBob/zkbob-client-js/pull/140/commits/f090a7df2a351da5ad9c03d53985a1c86dc73091

2023-06-21 13:38 UTC, EvgenKor commented on src/config.ts
> +  SaltedPermit = 'permit',  // EIP-2612 (regular permit)
Mentioned in https://github.com/zkBob/zkbob-client-js/pull/140/commits/b7c051f962b88a4532d9a609dc529d7217c43674

2023-06-21 13:39 UTC, EvgenKor commented on src/networks/evm.ts
> +    private erc3009?: Contract;
Good point. Merged in https://github.com/zkBob/zkbob-client-js/pull/140/commits/b7c051f962b88a4532d9a609dc529d7217c43674

2023-06-21 13:47 UTC, r0wdy1 approved these changes
lgtm

2023-06-21 13:48 UTC, r0wdy1 approved these changes

2023-06-21 14:38 UTC, k1rill-fedoseev approved these changes

2023-06-21 14:40 UTC, k1rill-fedoseev commented on src/signers/usdc-signer.ts
> +        };
This one is still valid 👀

2023-06-21 14:55 UTC, EvgenKor commented on src/networks/evm.ts
> +        this.tokenContract().options.address = permit2Address;
> Do you think it's safe to reassign contract address each time with a different value?
It's just a network backend which should be a chain universal communicating point without linking to the concrete pool deployment. Such approach allow us to reuse single network backend (`EvmNetwork` instance) for the different pools on that chain. We create NetworkBackend instances for the all configured chains on the library initilization to reduce pool switching time. Creating a backend for the each pool may cause memory wasting in case of a lot of pools in the config

> Seems like we can break something if we'll forget to update it someplace in the code?
I think it's a code review main purpose to avoid that case :)

2023-06-21 16:31 UTC, EvgenKor commented on src/signers/usdc-signer.ts
> +        };
Hmm, I agree about domains differences. But the implementation becomes not so easy as assumed. I noted the Metamask doesn't support typed message signing requests with precomputed domain separator (and it's ok because it should verify provided parameters for `domain` message are valid). So I must provide EIP712Domain type and associated domain message to the UI to proceed with the signing request. And I cannot find appropriate way except hardcoding it via configuration variables. Any ideas? Is I miss something?

2023-06-21 17:05 UTC, EvgenKor commented on src/signers/usdc-signer.ts
> +        };
Okay, I think it's a good temporary solution. I renamed `TransferWithAuthSigner` to `PolygonUSDCSigner` and `DepositType.TransferWithAuth` to `DepositType.AuthPolygonUSDC` https://github.com/zkBob/zkbob-client-js/pull/140/commits/90f70159ebca8fb8f17284890fcc5a1641dac7e3

2023-06-22 07:33 UTC, AllFi approved these changes

2023-06-22 11:05 UTC, merged