Add ability to use delegated prover
zkBob/zkbob-client-js pull request #72
Opened 2022-12-22 15:09 UTC by AllFi

2022-12-28 07:30 UTC, LyzeOfKiel commented on src/client.ts
> +      if (token.delegatedProverUrl) {
Maybe we can remove conditional nesting here? Just a code style suggestion.

2022-12-28 07:30 UTC, LyzeOfKiel approved these changes

2022-12-28 07:55 UTC, AllFi commented on src/client.ts
> +      if (token.delegatedProverUrl) {
I also thought about it but then we can't handle separately the case when delegated prover was enabled but delegated prover url wasn't provided. And it seems to me that it's not correct to use worker's prover in the case. What do you think?

2022-12-28 08:44 UTC, k1rill-fedoseev commented on src/client.ts
> +      if (token.delegatedProverUrl) {
I think we can always try to fallback to a local prover, if a remote prover can't be used. This way we can show user an error only in cases where both provers don't work.

2022-12-28 08:44 UTC, k1rill-fedoseev commented on src/client.ts
> +  public setDelegatedProverEnabled(tokenAddress: string, enabled: boolean) {
We expect UI to call this function with true flag on startup on mobile devices, right?

2022-12-28 08:58 UTC, AllFi commented on src/client.ts
> +  public setDelegatedProverEnabled(tokenAddress: string, enabled: boolean) {
I am not sure. The public and private inputs that the user sends are enough to reveal all history of the user's transactions. I think it is not fair to use delegated prover without warning the user.

2022-12-28 09:08 UTC, EvgenKor commented on src/client.ts
> +      if (token.delegatedProverUrl) {
> we can't handle separately the case when delegated prover was enabled but delegated prover url wasn't provided.

But you can check url presence in `setDelegatedProverEnabled` function when enabling is required. Also during client initialising you can check such case in the `Token` object and force disable delegate prover in case of prover URL absence

And I agree with @k1rill-fedoseev we should to use the local prover in case of any issues with delegated one. The throw cases should be minimized in a case of user cannot influence on it

2022-12-28 09:10 UTC, EvgenKor commented on src/client.ts
> +  public setDelegatedProverEnabled(tokenAddress: string, enabled: boolean) {
Is it supposed we can disable prover during the work? As I see the enabled flag is primarily set during the initialize stage

2022-12-28 09:14 UTC, AllFi commented on src/client.ts
> +      if (token.delegatedProverUrl) {
Alright, it makes sense. I'll prepare updates.

2022-12-28 09:30 UTC, AllFi commented on src/client.ts
> +  public setDelegatedProverEnabled(tokenAddress: string, enabled: boolean) {
If I remember correctly we planned to add in user settings some checkbox that controls using of the delegated prover.

2022-12-28 11:32 UTC, AllFi commented on src/client.ts
> +      if (token.delegatedProverUrl) {
Fixed it in https://github.com/zkBob/zkbob-client-js/pull/72/commits/b6f6c81d1c065e8f901f64a3377ce7eff8100f71.

2022-12-28 12:25 UTC, EvgenKor approved these changes
Currently all is fine. Just a small proposal for the future. Since we send some sensitive data here, to ensure the prover is active and honest we can add some kind of authentication. E.g. we can add an endpoint `/auth`. By requesting that endpoint the prover will calculate signature from the incoming message. Then client library can restore prover public key and compare it with hardcoded array. If it has any matching we accept that prover (we'll know the prover is in active state and it's honest one). The honest prover's public keys can be published in docs for example. This checking should be done before prover enabling. Wdyt?

2022-12-28 12:53 UTC, AllFi commented
> Currently all is fine. Just a small proposal for the future. Since we send some sensitive data here, to ensure the prover is active and honest we can add some kind of authentication. E.g. we can add an endpoint `/auth`. By requesting that endpoint the prover will calculate signature from the incoming message. Then client library can restore prover public key and compare it with hardcoded array. If it has any matching we accept that prover (we'll know the prover is in active state and it's honest one). The honest prover's public keys can be published in docs for example. This checking should be done before prover enabling. Wdyt?

Yes, we definitely need to add server authentication. I'll prepare a separate PR if you don't mind.

2022-12-28 13:40 UTC, LyzeOfKiel commented
Btw, maybe it makes sense to compare proof public inputs returned by a delegated prover with ones provided by user(as well as verify the proof itself, but as I know it is already implemented)? Because, now, prover can easily use some other memo input thus breaking a user's transaction, for example.

2022-12-28 13:55 UTC, AllFi commented
> Btw, maybe it makes sense to compare proof public inputs returned by a delegated prover with ones provided by user(as well as verify the proof itself, but as I know it is already implemented)? Because, now, prover can easily use some other memo input thus breaking a user's transaction, for example.

I agree, I'll prepare changes.

2022-12-28 14:43 UTC, EvgenKor commented
> I agree, I have prepared changes.

But what did you solve with the latest commit (https://github.com/zkBob/zkbob-client-js/pull/72/commits/794173614815a2ac69dbd0883e9b4061c0a20ec2)? If the delegate prover returned proof with the incorrect inputs the tx proof will considered incorrect and the user will unable to send tx. Maybe it's better to compare inputs returned from the delegate prover (`txProof.inputs`) with the origin inputs (`txData.public`). And in case of mismatching run local prover as a fallback?

2022-12-28 14:49 UTC, AllFi commented
> > I agree, I have prepared changes.
> 
> But what did you solve with the latest commit ([7941736](https://github.com/zkBob/zkbob-client-js/commit/794173614815a2ac69dbd0883e9b4061c0a20ec2))? If the delegate prover returned proof with the incorrect inputs the tx proof will considered incorrect and the user will unable to send tx. Maybe it's better to compare inputs returned from the delegate prover (`txProof.inputs`) with the origin inputs (`txData.public`). And in case of mismatching run local prover as a fallback?

Prover can also compute invalid proof but return correct inputs so it seems that we need to introduce additional proof verification for delegated prover.

2022-12-28 14:53 UTC, EvgenKor commented
> > > I agree, I have prepared changes.
> > 
> > 
> > But what did you solve with the latest commit ([7941736](https://github.com/zkBob/zkbob-client-js/commit/794173614815a2ac69dbd0883e9b4061c0a20ec2))? If the delegate prover returned proof with the incorrect inputs the tx proof will considered incorrect and the user will unable to send tx. Maybe it's better to compare inputs returned from the delegate prover (`txProof.inputs`) with the origin inputs (`txData.public`). And in case of mismatching run local prover as a fallback?
> 
> Prover can also compute invalid proof but return correct inputs so it seems that we need to introduce additional proof verification for delegated prover.

Let's move proof verification from the tx creation functions to the `this.proveTx` to reduce code length. And yes, we should check both inputs and proofs as well

2022-12-28 14:54 UTC, EvgenKor commented
And I think we should return an TxProofError **_only_** after the local prover returns incorrect proof

2022-12-28 15:38 UTC, AllFi commented
1. Remove inputs from delegated prover response because inputs are not necessary actually

2023-01-03 08:22 UTC, k1rill-fedoseev approved these changes

2023-01-03 08:22 UTC, k1rill-fedoseev commented on src/worker.ts
> +    return new Promise(async (resolve, reject) => {
I am almost sure the following code will have absolutely the same semantics:
```javascript
async verifyTxProof(inputs: string[], proof: SnarkProof): Promise<boolean> {
  return wasm.Proof.verify(transferVk!, inputs, proof);
}
```

2023-01-03 08:22 UTC, k1rill-fedoseev commented on src/client.ts
> +  private async proveTx(tokenAddres: string, pub: any, sec: any): Promise<any> {
`tokenAddres` -> `tokenAddress`

2023-01-03 09:42 UTC, AllFi commented on src/worker.ts
> +    return new Promise(async (resolve, reject) => {
Yes, it seems so. Probably, we can refactor almost all methods in worker.js. @EvgenKor what do you think?

2023-01-03 12:54 UTC, AllFi commented
I'm not sure about implementing params lazy load in this pr. It depends on implementation. If we want to add lazy load only for the case when delegated prover is down we can include updates in this pr. If we want to add a global lazy load I think it is better to do it in a new pr. Wdyt?

2023-01-03 12:56 UTC, EvgenKor commented
> I'm not sure about implementing params lazy load in this pr. It depends on implementation. If we want to add lazy load only for the case when delegated prover is down we can include updates in this pr. If we want to add a global lazy load I think it is better to do it in a new pr. Wdyt?

I think it should be a globally feature in the separated PR

2023-01-03 13:49 UTC, EvgenKor commented on src/worker.ts
> +    return new Promise(async (resolve, reject) => {
Not sure about that. I remember that in such case the errors happened inside wasm may not covered in `reject`. It's need to check that case

2023-01-03 14:02 UTC, AllFi commented on src/worker.ts
> +    return new Promise(async (resolve, reject) => {
Let's move it to pr with lazy loading. It will be necessary to retest all anyway. I can additionally check this refactoring.

2023-01-06 16:07 UTC, AllFi commented
It is necessary to support three modes of prover:
1. Only local prover
2. Only delegated prover
3. Delegated prover with fallback to the local prover

2023-01-09 12:13 UTC, k1rill-fedoseev approved these changes

2023-01-10 07:13 UTC, EvgenKor requested changes

2023-01-10 07:13 UTC, EvgenKor commented on src/client.ts
> +          throw new InternalError(`Failed to prove tx using delegated prover: ${e}`);
Let's throw `TxProofError` here instead `InternalError`. The error details can be logged through `console.error`

2023-01-10 08:37 UTC, akolotov requested changes

2023-01-10 08:37 UTC, akolotov commented on src/client.ts
> +        const headers = {'content-type': 'application/json;charset=UTF-8'};
Consider to send the support id to the prover in the same manner as it is sent to the relayer.

2023-01-10 08:37 UTC, akolotov commented on src/client.ts
> +    if ((mode == ProverMode.Delegated || mode == ProverMode.DelegatedWithFallback) && !token.delegatedProverUrl) {
Consider to have a handshake action with the prover to identify on this phase that provided URL is not valid. For example, the action could be to get the prover's version. If the prover URL is valid the version of the prover could be displayed in UI then. Otherwise, we can through `InternalError`.

2023-01-10 08:50 UTC, AllFi commented on src/client.ts
> +          throw new InternalError(`Failed to prove tx using delegated prover: ${e}`);
Done in https://github.com/zkBob/zkbob-client-js/pull/72/commits/53a1d2a4babe58f20dc83883c0cad1f69b7bc177

2023-01-10 09:53 UTC, AllFi commented on src/client.ts
> +        const headers = {'content-type': 'application/json;charset=UTF-8'};
Yes, it definitely makes sense.

2023-01-10 09:54 UTC, AllFi commented on src/client.ts
> +    if ((mode == ProverMode.Delegated || mode == ProverMode.DelegatedWithFallback) && !token.delegatedProverUrl) {
Good idea, I'll do it.

2023-01-10 10:56 UTC, AllFi commented on src/client.ts
> +    if ((mode == ProverMode.Delegated || mode == ProverMode.DelegatedWithFallback) && !token.delegatedProverUrl) {
Maybe it makes sense to do this after this PR https://github.com/zkBob/zkbob-client-js/pull/83 will be merged? I think we can reuse some structs and functions to prevent code duplication.

2023-01-10 11:25 UTC, akolotov commented on src/client.ts
> +    if ((mode == ProverMode.Delegated || mode == ProverMode.DelegatedWithFallback) && !token.delegatedProverUrl) {
I have no objections. In order to track it we can make a separate issue. Moreover it will require changes on UI side as well as on the prover so the related issues can be created in each of three components.

2023-01-10 11:46 UTC, AllFi commented on src/client.ts
> +        const headers = {'content-type': 'application/json;charset=UTF-8'};
Done in https://github.com/zkBob/zkbob-client-js/pull/72/commits/f99618d31bf812876bc88cbda0adabe67826dcb8

2023-01-10 11:49 UTC, akolotov approved these changes

2023-01-10 11:54 UTC, EvgenKor approved these changes

2023-01-10 11:55 UTC, merged