Params lazy loading
zkBob/zkbob-client-js pull request #80
Opened 2023-01-04 12:28 UTC by AllFi

2023-01-10 08:59 UTC, akolotov commented on src/params.ts
> +    public load(wasm: any) {
A dummy question... Does it have any sense to check that loaded (cached?, downloaded?) params match with the verifier expected in the pool contract?

2023-01-11 08:30 UTC, AllFi commented on src/params.ts
> +    public load(wasm: any) {
I think it makes sense if the client sends tx to the pool directly. In our case even if the client's and pool's params are a match but are not a match to the relayer's, the relayer stops this tx anyway. So I think the relayer should check that its params are a match with the pool's params and lib should check that its params are a match to the relayer's params. Wdyt?

2023-01-11 08:31 UTC, AllFi commented on src/params.ts
> +    public load(wasm: any) {
We probably can implement both checks but it will slow down the params loading so I'm not sure.

2023-01-11 08:55 UTC, akolotov commented on src/params.ts
> +    public load(wasm: any) {
I think we can plan to do this after the moment when a multipool environment comes true.

2023-01-11 14:41 UTC, akolotov commented
> I am not sure if it is necessary to add downloading params state when a user tries to prove tx. In most cases, params will be ready or almost ready when user will calculate proof for the first tx. 

If params are not ready, will it be possible to notify users to wait for more time before params are downloaded completely?

2023-01-11 14:50 UTC, EvgenKor commented
> > I am not sure if it is necessary to add downloading params state when a user tries to prove tx. In most cases, params will be ready or almost ready when user will calculate proof for the first tx.
> 
> If params are not ready, will it be possible to notify users to wait for more time before params are downloaded completely?

I believe it's unneeded. I think it's bad idea to say user anything about params from the UX point of view. It's an unknown entity for the most of users. We can just silent finalize params downloading before the proving process. So in such **_rarely_** case the proving time will increased a bit

2023-01-11 19:24 UTC, EvgenKor requested changes

2023-01-11 19:24 UTC, EvgenKor commented on src/params.ts
> +        this.loadingPromise = new Promise(async (resolve, reject) => {
Since this method is public let's suppose somebody invoke the `load` method multiple times while params are not currently loaded (due to any logic or code error in the library for example). It cause to params downloading multiple times because Promises have uncanceled nature. You can avoid it by checking promise existence (and setting it to undefined in the end of downloading)

2023-01-12 10:41 UTC, AllFi commented on src/client.ts
> +          client.worker.loadTxParams();
Params will be loaded in proveTx anyway in this case. But I agree that the sooner the better. Done in https://github.com/zkBob/zkbob-client-js/pull/80/commits/741dcafb3f7f5c44a0deef768e97272700340053

2023-01-12 10:42 UTC, AllFi commented on src/index.ts
> +      statusCallback({ state: InitState.InitWorker, download: lastProgress });
Yes, of course. I missed it. Done in https://github.com/zkBob/zkbob-client-js/pull/80/commits/741dcafb3f7f5c44a0deef768e97272700340053

2023-01-12 10:42 UTC, AllFi commented on src/params.ts
> +        this.loadingPromise = new Promise(async (resolve, reject) => {
Yep, it makes sense. Done in https://github.com/zkBob/zkbob-client-js/pull/80/commits/741dcafb3f7f5c44a0deef768e97272700340053

2023-01-12 12:12 UTC, EvgenKor requested changes

2023-01-12 12:14 UTC, EvgenKor commented on src/params.ts
> +        return await this.loadingPromise;
```suggestion
        if (this.needToLoad()) {
            this.load(wasm);
            
            return await this.loadingPromise;
        }
        
        return this.params;
```

Do not diffuse state machine logic between different functions

2023-01-12 12:26 UTC, AllFi commented on src/params.ts
> +        return await this.loadingPromise;
If params are loading now we still want to await the promise.

2023-01-12 12:27 UTC, AllFi commented on src/params.ts
> +        return await this.loadingPromise;
I mean if this.loadingStatus == LoadingStatus.InProgress

2023-01-12 12:36 UTC, AllFi commented on src/params.ts
> +    loadingStatus: LoadingStatus;
Agreed. Fixed in https://github.com/zkBob/zkbob-client-js/pull/80/commits/1988dd074c621d28ef3592b47866701373421f00

2023-01-12 12:40 UTC, EvgenKor commented on src/params.ts
> +        return await this.loadingPromise;
It's all just about the code clarity, the common logic is correct anyway

2023-01-12 12:49 UTC, AllFi commented on src/params.ts
> +        return await this.loadingPromise;
Agreed, it looks simpler this way.

2023-01-12 13:35 UTC, AllFi commented on src/params.ts
> +        return await this.loadingPromise;
Done: https://github.com/zkBob/zkbob-client-js/pull/80/commits/e70548515e8601111c819bba8ada9ddf6176328c

2023-01-12 13:57 UTC, EvgenKor approved these changes

2023-01-23 08:18 UTC, k1rill-fedoseev approved these changes

2023-01-24 08:42 UTC, merged